# permissions for end users to view visitorsapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: helm-operator
    app.kubernetes.io/managed-by: kustomize
  name: visitorsapp-viewer-role
rules:
- apiGroups:
  - example.example.com
  resources:
  - visitorsapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.example.com
  resources:
  - visitorsapps/status
  verbs:
  - get
